package combat_tracker.record;

import java.util.List;
import java.util.Locale;

/**
 * Renders a {@link SessionData} into the self-contained HTML report.
 *
 * <p>No Minecraft imports on purpose — see {@link SessionData}. Everything here is
 * string building and arithmetic, so {@link ReportPreview} can render a synthetic
 * session and prove the charts are right without starting the game.</p>
 */
public final class ReportBuilder {
    /** Vanilla melee range, drawn as a reference line on the reach chart. */
    private static final double VANILLA_REACH = 3.0;
    /** Standing player hitbox, drawn to scale on the aim scatter. */
    private static final double HITBOX_HALF_W = 0.3;
    private static final double HITBOX_HALF_H = 0.9;

    private static final int HIT_COLOR = 0x4caf50;
    private static final int MISS_COLOR = 0xef5350;
    private static final int COMBO_COLOR = 0x29b6f6;

    /**
     * Greys inside the charts.
     *
     * <p>Named here because they were the last colours still written inline at each
     * use, and they had drifted below the contrast floor unnoticed: on the
     * {@code #161a20} chart the tick labels sat at 3.7:1, the unit caption at 2.3:1
     * and the empty-chart label at 3.1:1, against the 4.5:1 that text of this size
     * needs. {@link #HITBOX} is a graphic rather than text, so it answers to the
     * 3:1 floor instead.</p>
     */
    private static final String AXIS_TX = "#828c99";
    private static final String NODATA = "#9aa4b2";
    private static final String HITBOX = "#6b7480";

    private ReportBuilder() {
    }

    public static String build(SessionData d, String sha, String sig, String canonical) {
        StringBuilder s = new StringBuilder(16384);
        s.append("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        s.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        s.append("<title>Combat Tracker session ").append(esc(d.startUtc)).append("</title><style>");
        s.append(css());
        s.append("</style></head><body><main>");

        identity(s, d);

        header(s, d);
        jumpSection(s, d);
        comboSection(s, d);
        reachSection(s, d);
        aimSection(s, d);
        integritySection(s, sha, sig, canonical);

        s.append("<p class=\"sub\">Generated by Combat Tracker. Charts are SVG embedded in this file.</p>");
        s.append("</main><script>").append(chartScript()).append("</script>");
        s.append("</body></html>");
        return s.toString();
    }

    /** One titled block. In one place so the sections cannot drift apart. */
    private static void openSection(StringBuilder s, String title) {
        s.append("<section><h2>").append(esc(title)).append("</h2>");
    }

    /** A single fact, as a chip rather than one more clause in a sentence. */
    private static void chip(StringBuilder s, String text) {
        s.append("<span class=\"chip\">").append(text).append("</span>");
    }

    // ── Sections ─────────────────────────────────────────────────────────────

    /**
     * Skin, name and opponents, matching the online viewer so a saved report and a
     * shared link look like the same product.
     *
     * <p>The heads come from a head-render service, which is the one thing on the
     * page that needs the network. Opening a report offline simply drops the images
     * and keeps every number, so nothing important depends on it.</p>
     */
    private static void identity(StringBuilder s, SessionData d) {
        s.append("<header class=\"hero\">").append(head(d.playerUuid, 76, "hero__avatar"));
        s.append("<div class=\"hero__text\">");
        s.append("<h1>").append(d.title == null || d.title.isEmpty()
                ? "Combat Tracker session" : esc(d.title)).append("</h1>");
        s.append("<div class=\"hero__ign\">").append(esc(d.player)).append("</div>");

        if (!d.opponents.isEmpty()) {
            s.append("<div class=\"vs\"><span class=\"vs__label\">vs</span>");
            for (String o : d.opponents) {
                s.append("<span>").append(head(o, 22, null)).append(" ").append(esc(o)).append("</span>");
            }
            s.append("</div>");
        }

        long durS = Math.max(0, (d.endEpochMs - d.startEpochMs) / 1000);
        s.append("<div class=\"meta\">");
        chip(s, esc(d.startUtc));
        chip(s, durS / 60 + "m " + durS % 60 + "s");
        chip(s, Math.round(d.pingMs) + " ms ping");
        s.append("</div></div></header>");

        s.append("<p class=\"sub\">Charts: <b>click a point for its exact value</b>, scroll to zoom, ")
                .append("drag to pan, double-click to reset.</p>");
    }

    /**
     * A player head by UUID or name. Anything outside the character set a Minecraft
     * name or UUID can contain is stripped, so nothing from a session can break out
     * of the URL or the attribute.
     *
     * <p>Width and height are stated so the row does not reflow when the image lands,
     * which matters more here than online: a report opened offline never resolves
     * these at all, and the layout should be identical either way.</p>
     */
    private static String head(String idOrName, int size, String cls) {
        String safe = idOrName == null ? "" : idOrName.replaceAll("[^A-Za-z0-9_-]", "");
        if (safe.isEmpty()) {
            return "";
        }
        return "<img class=\"" + (cls == null ? "" : cls) + "\" "
                + "src=\"https://mc-heads.net/avatar/" + safe + "/" + size + "\" alt=\"\" "
                + "width=\"" + size + "\" height=\"" + size + "\" loading=\"lazy\" "
                + "onerror=\"this.style.visibility='hidden'\">";
    }

    private static void header(StringBuilder s, SessionData d) {
        openSection(s, "Session");
        s.append("<table><tr><th>Start (time signature)</th><td>").append(esc(d.startUtc))
                .append(" <span class=\"sub\">(epoch ").append(d.startEpochMs).append(")</span></td></tr>");
        s.append("<tr><th>End (time signature)</th><td>").append(esc(d.endUtc))
                .append(" <span class=\"sub\">(epoch ").append(d.endEpochMs).append(")</span></td></tr>");
        long durS = Math.max(0, (d.endEpochMs - d.startEpochMs) / 1000);
        s.append("<tr><th>Duration</th><td>").append(durS / 60).append("m ").append(durS % 60).append("s</td></tr>");
        s.append("<tr><th>Player UUID</th><td>").append(esc(d.playerUuid)).append("</td></tr>");
        s.append("<tr><th>Ping (session average)</th><td>").append(Math.round(d.pingMs))
                .append(" ms <span class=\"sub\">(recorded for context; it adjusts no measurement)</span></td></tr>");
        s.append("</table></section>");
    }

    private static void jumpSection(StringBuilder s, SessionData d) {
        openSection(s, "Jump resets");
        s.append("<div class=\"cards\">");
        card(s, Integer.toString(d.jumpAttempts), "attempts");
        card(s, Integer.toString(d.jumpHits), "hits");
        card(s, Integer.toString(d.jumpMisses), "misses");
        card(s, fmt(d.jumpAvgMs) + " ms", "avg delta");
        card(s, fmt(d.jumpSdMs) + " ms", "std dev");
        s.append("</div>");
        s.append(chartBlock(timeChart("Jump-reset delta over time (ms)", d.jumpEvents, d.startEpochMs, d.endEpochMs)));
        s.append("</section>");
    }

    private static void comboSection(StringBuilder s, SessionData d) {
        openSection(s, "Combo timing");
        s.append("<div class=\"cards\">");
        card(s, Integer.toString(d.combos), "combos");
        card(s, Integer.toString(d.comboIntervals), "intervals");
        card(s, fmt(d.comboAvgMs) + " ms", "avg interval");
        card(s, fmt(d.comboJitterMs) + " ms", "jitter (SD)");
        s.append("</div>");
        s.append(chartBlock(comboChart(d)));
        s.append("</section>");
    }

    private static void reachSection(StringBuilder s, SessionData d) {
        openSection(s, "Reach");
        s.append("<div class=\"cards\">");
        card(s, Integer.toString(d.swings), "swings");
        card(s, Integer.toString(d.swingHits), "landed");
        card(s, Integer.toString(d.swingMisses), "whiffed");
        card(s, fmt(d.reachAvgBlocks) + " b", "avg reach");
        card(s, fmt(d.reachMaxBlocks) + " b", "max reach");
        card(s, fmt(d.reachSdBlocks) + " b", "std dev");
        s.append("</div>");
        s.append("<p class=\"sub\">Green landed, red whiffed. Dashed line is vanilla melee range.</p>");
        s.append(chartBlock(reachChart(d)));
        s.append("</section>");
    }

    private static void aimSection(StringBuilder s, SessionData d) {
        openSection(s, "Aim placement");
        s.append("<div class=\"cards\">");
        card(s, fmt(d.aimAvgDeg) + "&deg;", "avg off-centre");
        card(s, fmt(d.aimSdDeg) + "&deg;", "std dev");
        s.append("</div>");
        s.append("<p class=\"sub\">Hitbox drawn to scale. Green landed, red whiffed.</p>");
        s.append(chartBlock(aimScatter(d)));
        s.append("</section>");
    }

    private static void integritySection(StringBuilder s, String sha, String sig, String canonical) {
        openSection(s, "Integrity");
        s.append("<div class=\"intg\">");
        s.append("Algorithm: SHA-256 + HMAC-SHA256<br>SHA-256: ").append(esc(sha))
                .append("<br>Signature: ").append(esc(sig));
        s.append("<br><span class=\"warn\">Note:</span> the signing key ships inside the open-source mod, so this "
                + "detects casual edits but is <b>not</b> unforgeable. Verify by recomputing SHA-256 over the exact "
                + "canonicalData string below (UTF-8).");
        s.append("<br><br><span class=\"warn\">On reach and aim:</span> measured on your own client, where other "
                + "players are interpolated locally, so these will not match a server-side anti-cheat exactly.</div>");
        s.append("<details><summary>Canonical data (hashed bytes)</summary><pre>")
                .append(esc(canonical)).append("</pre></details></section>");
    }

    // ── Charts ───────────────────────────────────────────────────────────────

    private static final int W = 1400;
    private static final int H = 300;
    private static final int ML = 48;
    private static final int MR = 16;
    private static final int MT = 28;
    private static final int MB = 30;

    private static String timeChart(String title, List<SessionData.JEvent> pts, long startMs, long endMs) {
        StringBuilder s = svgOpen(W, H);
        title(s, title);
        if (pts.isEmpty()) {
            return noData(s);
        }
        double yMin = 0, yMax = 1;
        for (SessionData.JEvent p : pts) {
            yMax = Math.max(yMax, p.deltaMs);
            yMin = Math.min(yMin, p.deltaMs);
        }
        yMax = yMax * 1.1 + 1;
        long span = Math.max(1, endMs - startMs);
        axes(s, yMin, yMax, "ms");

        int pw = W - ML - MR, ph = H - MT - MB;
        StringBuilder poly = new StringBuilder();
        StringBuilder dots = new StringBuilder();
        for (SessionData.JEvent p : pts) {
            int x = (int) (ML + (double) (p.t - startMs) / span * pw);
            int y = (int) (MT + ph - (p.deltaMs - yMin) / (yMax - yMin) * ph);
            poly.append(x).append(",").append(y).append(" ");
            boolean ok = "SUCCESS".equals(p.result);
            String tip = offset(p.t - startMs) + " : " + p.deltaMs + " ms"
                    + (p.result != null ? " (" + p.result + ")" : "");
            dot(dots, x, y, ok ? HIT_COLOR : MISS_COLOR, tip);
        }
        s.append("<polyline points=\"").append(poly.toString().trim())
                .append("\" fill=\"none\" stroke=\"#4caf50\" stroke-opacity=\"0.35\" stroke-width=\"1\"/>");
        s.append(dots).append("</svg>");
        return s.toString();
    }

    private static String comboChart(SessionData d) {
        StringBuilder s = svgOpen(W, H);
        title(s, "Combo inter-hit interval over time (ms)");
        if (d.comboEvents.isEmpty()) {
            return noData(s);
        }
        double yMin = 0, yMax = 1;
        for (SessionData.CEvent c : d.comboEvents) {
            yMax = Math.max(yMax, c.intervalMs);
        }
        yMax = yMax * 1.1 + 1;
        long span = Math.max(1, d.endEpochMs - d.startEpochMs);
        axes(s, yMin, yMax, "ms");

        int pw = W - ML - MR, ph = H - MT - MB;
        StringBuilder poly = new StringBuilder();
        StringBuilder dots = new StringBuilder();
        for (SessionData.CEvent c : d.comboEvents) {
            int x = (int) (ML + (double) (c.t - d.startEpochMs) / span * pw);
            int y = (int) (MT + ph - (c.intervalMs - yMin) / (yMax - yMin) * ph);
            poly.append(x).append(",").append(y).append(" ");
            dot(dots, x, y, COMBO_COLOR, offset(c.t - d.startEpochMs) + " : " + c.intervalMs + " ms");
        }
        s.append("<polyline points=\"").append(poly.toString().trim())
                .append("\" fill=\"none\" stroke=\"#29b6f6\" stroke-opacity=\"0.5\" stroke-width=\"1\"/>");
        s.append(dots).append("</svg>");
        return s.toString();
    }

    private static String reachChart(SessionData d) {
        StringBuilder s = svgOpen(W, H);
        title(s, "Reach per swing (blocks)");
        if (d.swingEvents.isEmpty()) {
            return noData(s);
        }
        double yMax = VANILLA_REACH;
        for (SessionData.SEvent e : d.swingEvents) {
            yMax = Math.max(yMax, e.reach);
        }
        yMax = yMax * 1.15;
        long span = Math.max(1, d.endEpochMs - d.startEpochMs);
        axes(s, 0, yMax, "blocks");

        int pw = W - ML - MR, ph = H - MT - MB;

        // Vanilla-range reference line.
        int refY = (int) (MT + ph - VANILLA_REACH / yMax * ph);
        s.append("<line x1=\"").append(ML).append("\" y1=\"").append(refY).append("\" x2=\"").append(ML + pw)
                .append("\" y2=\"").append(refY)
                .append("\" stroke=\"#ffb454\" stroke-width=\"1\" stroke-dasharray=\"4 4\"/>");
        s.append("<text x=\"").append(ML + pw).append("\" y=\"").append(refY - 4)
                .append("\" fill=\"#ffb454\" font-size=\"10\" text-anchor=\"end\" font-family=\"sans-serif\">")
                .append("vanilla 3.0</text>");

        StringBuilder dots = new StringBuilder();
        for (SessionData.SEvent e : d.swingEvents) {
            int x = (int) (ML + (double) (e.t - d.startEpochMs) / span * pw);
            int y = (int) (MT + ph - e.reach / yMax * ph);
            String who = e.target >= 0 && e.target < d.opponents.size() ? " vs " + d.opponents.get(e.target) : "";
            dot(dots, x, y, e.hit ? HIT_COLOR : MISS_COLOR,
                    offset(e.t - d.startEpochMs) + " : " + fmt(e.reach) + " blocks "
                            + (e.hit ? "(landed)" : "(whiffed)") + who);
        }
        s.append(dots).append("</svg>");
        return s.toString();
    }

    /**
     * Scatter of aim offsets with the hitbox drawn to scale. Both axes share one
     * scale so the box keeps its real 0.6 x 1.8 proportions — squashing it to fill
     * the frame would make centred aim look more spread out than it is.
     */
    private static String aimScatter(SessionData d) {
        int w = 420, h = 460, ml = 44, mr = 16, mt = 28, mb = 34;
        int pw = w - ml - mr, ph = h - mt - mb;
        StringBuilder s = svgOpen(w, h, 520);
        title(s, "Aim offset from hitbox centre (blocks)");
        if (d.swingEvents.isEmpty()) {
            return noData(s, w, h);
        }

        double halfW = HITBOX_HALF_W * 1.6;
        double halfH = HITBOX_HALF_H * 1.25;
        for (SessionData.SEvent e : d.swingEvents) {
            halfW = Math.max(halfW, Math.abs(e.offX) * 1.1);
            halfH = Math.max(halfH, Math.abs(e.offY) * 1.1);
        }
        // One scale for both axes keeps the hitbox honest.
        double scale = Math.min(pw / (2 * halfW), ph / (2 * halfH));
        double cx = ml + pw / 2.0;
        double cy = mt + ph / 2.0;

        // Hitbox outline.
        double bw = HITBOX_HALF_W * scale, bh = HITBOX_HALF_H * scale;
        s.append("<rect x=\"").append(r(cx - bw)).append("\" y=\"").append(r(cy - bh))
                .append("\" width=\"").append(r(bw * 2)).append("\" height=\"").append(r(bh * 2))
                .append("\" fill=\"#4caf50\" fill-opacity=\"0.06\" stroke=\"").append(HITBOX)
                .append("\" stroke-width=\"1\"/>");
        // Centre crosshair.
        s.append("<line x1=\"").append(r(cx)).append("\" y1=\"").append(mt).append("\" x2=\"").append(r(cx))
                .append("\" y2=\"").append(mt + ph).append("\" stroke=\"#2a2f37\"/>");
        s.append("<line x1=\"").append(ml).append("\" y1=\"").append(r(cy)).append("\" x2=\"").append(ml + pw)
                .append("\" y2=\"").append(r(cy)).append("\" stroke=\"#2a2f37\"/>");

        StringBuilder dots = new StringBuilder();
        for (SessionData.SEvent e : d.swingEvents) {
            double x = cx + e.offX * scale;
            double y = cy - e.offY * scale;
            String who = e.target >= 0 && e.target < d.opponents.size() ? " vs " + d.opponents.get(e.target) : "";
            dots.append("<circle cx=\"").append(r(x)).append("\" cy=\"").append(r(y))
                    .append("\" r=\"3\" fill=\"").append(hex(e.hit ? HIT_COLOR : MISS_COLOR))
                    .append("\" fill-opacity=\"0.75\"><title>")
                    .append(esc(fmt(e.offX) + ", " + fmt(e.offY) + " blocks / " + fmt(e.aimDeg) + " deg" + who))
                    .append("</title></circle>");
        }
        s.append(dots);
        s.append("<text x=\"").append(ml).append("\" y=\"").append(h - 10)
                .append("\" fill=\"").append(AXIS_TX).append("\" font-size=\"10\" font-family=\"sans-serif\">")
                .append("box = player hitbox to scale &middot; green landed, red whiffed</text>");
        s.append("</svg>");
        return s.toString();
    }

    // ── SVG helpers ──────────────────────────────────────────────────────────

    private static StringBuilder svgOpen(int w, int h) {
        return svgOpen(w, h, null);
    }

    /**
     * @param maxWidthPx cap in CSS pixels, or null to fill the available width.
     *                   The scatter is squarish and looks wrong stretched; the
     *                   time-series charts are better the wider they get.
     */
    private static StringBuilder svgOpen(int w, int h, Integer maxWidthPx) {
        StringBuilder s = new StringBuilder(2048);
        // A capped chart is also marked, because the mobile min-width that keeps the
        // wide time-series readable would otherwise beat the cap — min-width wins over
        // max-width — and inflate the squarish scatter to full height on a phone.
        s.append("<svg class=\"chart").append(maxWidthPx == null ? "" : " chart--fit")
                .append("\" viewBox=\"0 0 ").append(w).append(" ").append(h)
                .append("\" width=\"100%\" style=\"")
                .append(maxWidthPx == null ? "" : "max-width:" + maxWidthPx + "px;")
                .append("\">");
        return s;
    }

    private static void title(StringBuilder s, String text) {
        s.append("<text x=\"").append(ML).append("\" y=\"18\" fill=\"#9fb3c8\" font-size=\"13\" ")
                .append("font-family=\"sans-serif\">").append(esc(text)).append("</text>");
    }

    private static String noData(StringBuilder s) {
        return noData(s, W, H);
    }

    private static String noData(StringBuilder s, int w, int h) {
        s.append("<text x=\"").append(w / 2).append("\" y=\"").append(h / 2)
                .append("\" fill=\"").append(NODATA).append("\" font-size=\"13\" text-anchor=\"middle\" ")
                .append("font-family=\"sans-serif\">no data recorded</text></svg>");
        return s.toString();
    }

    /**
     * Y axis with gridlines on round values.
     *
     * <p>The old version drew exactly three lines at min/mid/max, which on a
     * millisecond axis produced labels like "37" and left a reader guessing at
     * everything between them. Milliseconds are the whole point of these charts,
     * so this picks a round step (1, 2, 2.5, 5, 10, ...) sized to the range and
     * labels every line.</p>
     */
    private static void axes(StringBuilder s, double yMin, double yMax, String unit) {
        int pw = W - ML - MR, ph = H - MT - MB;
        s.append("<line x1=\"").append(ML).append("\" y1=\"").append(MT).append("\" x2=\"").append(ML)
                .append("\" y2=\"").append(MT + ph).append("\" stroke=\"#2a2f37\"/>");
        s.append("<line x1=\"").append(ML).append("\" y1=\"").append(MT + ph).append("\" x2=\"").append(ML + pw)
                .append("\" y2=\"").append(MT + ph).append("\" stroke=\"#2a2f37\"/>");

        double step = niceStep(yMax - yMin, 6);
        double first = Math.ceil(yMin / step) * step;
        for (double val = first; val <= yMax + step * 0.001; val += step) {
            int yy = (int) (MT + ph - (val - yMin) / (yMax - yMin) * ph);
            if (yy < MT || yy > MT + ph) {
                continue;
            }
            boolean zero = Math.abs(val) < step * 0.001;
            s.append("<line x1=\"").append(ML - 3).append("\" y1=\"").append(yy).append("\" x2=\"").append(ML + pw)
                    .append("\" y2=\"").append(yy).append("\" stroke=\"").append(zero ? "#3a424d" : "#21262e")
                    .append("\"/>");
            s.append("<text x=\"").append(ML - 6).append("\" y=\"").append(yy + 3)
                    .append("\" fill=\"").append(AXIS_TX)
                    .append("\" font-size=\"10\" text-anchor=\"end\" font-family=\"sans-serif\">")
                    .append(tick(val, step)).append("</text>");
        }
        if (unit != null) {
            s.append("<text x=\"").append(ML - 6).append("\" y=\"").append(MT - 8)
                    .append("\" fill=\"").append(AXIS_TX)
                    .append("\" font-size=\"9\" text-anchor=\"end\" font-family=\"sans-serif\">")
                    .append(esc(unit)).append("</text>");
        }
    }

    /** Rounds a raw axis step up to the nearest 1 / 2 / 2.5 / 5 / 10 x power of ten. */
    private static double niceStep(double range, int targetLines) {
        double raw = Math.max(1.0e-9, range / Math.max(1, targetLines));
        double mag = Math.pow(10, Math.floor(Math.log10(raw)));
        double norm = raw / mag;
        double step;
        if (norm <= 1.0) {
            step = 1.0;
        } else if (norm <= 2.0) {
            step = 2.0;
        } else if (norm <= 2.5) {
            step = 2.5;
        } else if (norm <= 5.0) {
            step = 5.0;
        } else {
            step = 10.0;
        }
        return step * mag;
    }

    private static void dot(StringBuilder s, int x, int y, int color, String tip) {
        s.append("<circle cx=\"").append(x).append("\" cy=\"").append(y).append("\" r=\"3\" fill=\"")
                .append(hex(color)).append("\"><title>").append(esc(tip)).append("</title></circle>");
    }

    /**
     * Pan, zoom, and click-to-read. Shared verbatim with the online viewer in
     * {@code docs/index.html} — if you change one, change the other.
     *
     * <p>A click selects the <em>nearest</em> point rather than requiring a direct
     * hit on it: the dots are three pixels across, and on a dense chart hitting one
     * exactly is not realistic. The search radius is scaled by the current zoom so
     * it stays constant on screen.</p>
     *
     * <p>Drags are excluded by distance travelled, otherwise every pan would end by
     * selecting whatever happened to be under the cursor.</p>
     */
    private static String chartScript() {
        return "document.querySelectorAll('svg.chart').forEach(function(svg){"
                + "var vb=svg.getAttribute('viewBox').split(' ').map(Number);var init=vb.slice();"
                + "var v={x:vb[0],y:vb[1],w:vb[2],h:vb[3]};"
                + "function ap(){svg.setAttribute('viewBox',v.x+' '+v.y+' '+v.w+' '+v.h);}"
                // Found from the .chartwrap, not the immediate parent. The chart sits
                // inside a scroller so it can keep a readable width on a phone, which
                // puts a div between the svg and its readout — parentNode looked right
                // and silently returned null, leaving click-to-read nowhere to print.
                + "var out=svg.closest('.chartwrap').querySelector('.readout');var sel=null;"
                + "function clear(){if(sel){sel.removeAttribute('data-sel');sel=null;}"
                + "if(out){out.textContent=out.getAttribute('data-hint');out.classList.remove('on');}}"
                + "function pick(c){if(sel)sel.removeAttribute('data-sel');sel=c;c.setAttribute('data-sel','1');"
                + "if(out){var t=c.querySelector('title');out.textContent=t?t.textContent:'';out.classList.add('on');}}"
                + "svg.addEventListener('wheel',function(e){e.preventDefault();var r=svg.getBoundingClientRect();"
                + "var mx=v.x+(e.clientX-r.left)/r.width*v.w;var my=v.y+(e.clientY-r.top)/r.height*v.h;"
                + "var f=e.deltaY<0?0.85:1/0.85;v.w*=f;v.h*=f;"
                + "v.x=mx-(e.clientX-r.left)/r.width*v.w;v.y=my-(e.clientY-r.top)/r.height*v.h;ap();},{passive:false});"
                + "var d=false,lx=0,ly=0,moved=0;"
                + "svg.addEventListener('mousedown',function(e){d=true;lx=e.clientX;ly=e.clientY;moved=0;"
                + "svg.style.cursor='grabbing';});"
                + "window.addEventListener('mousemove',function(e){if(!d)return;"
                + "moved+=Math.abs(e.clientX-lx)+Math.abs(e.clientY-ly);var r=svg.getBoundingClientRect();"
                + "v.x-=(e.clientX-lx)/r.width*v.w;v.y-=(e.clientY-ly)/r.height*v.h;lx=e.clientX;ly=e.clientY;ap();});"
                + "window.addEventListener('mouseup',function(){d=false;svg.style.cursor='grab';});"
                + "svg.addEventListener('click',function(e){"
                + "if(moved>4)return;"                     // that was a pan, not a click
                + "var r=svg.getBoundingClientRect();"
                + "var ux=v.x+(e.clientX-r.left)/r.width*v.w;var uy=v.y+(e.clientY-r.top)/r.height*v.h;"
                + "var best=null,bd=Infinity;"
                + "svg.querySelectorAll('circle').forEach(function(c){"
                + "var dx=+c.getAttribute('cx')-ux,dy=+c.getAttribute('cy')-uy;var dd=dx*dx+dy*dy;"
                + "if(dd<bd){bd=dd;best=c;}});"
                + "var lim=14*(v.w/init[2]);"              // constant on screen as you zoom
                + "if(best&&bd<=lim*lim)pick(best);else clear();});"
                + "function ease(a,b,t){return a+(b-a)*t;}"
                + "svg.addEventListener('dblclick',function(){"
                + "if(window.matchMedia&&window.matchMedia('(prefers-reduced-motion:reduce)').matches){"
                + "v={x:init[0],y:init[1],w:init[2],h:init[3]};ap();clear();return;}"
                + "var f={x:v.x,y:v.y,w:v.w,h:v.h},t0=performance.now();"
                + "(function step(now){var k=Math.min(1,(now-t0)/260);"
                + "var e=1-Math.pow(1-k,3);"                       // ease-out cubic
                + "v.x=ease(f.x,init[0],e);v.y=ease(f.y,init[1],e);"
                + "v.w=ease(f.w,init[2],e);v.h=ease(f.h,init[3],e);ap();"
                + "if(k<1)requestAnimationFrame(step);})(t0);clear();});"
                + "});"
                + "var rm=window.matchMedia&&window.matchMedia('(prefers-reduced-motion:reduce)').matches;"
                + "var targets=[].slice.call(document.querySelectorAll('h2,.cards,.chartwrap,table,.intg'));"
                + "function show(el){el.classList.add('shown');}"
                // Stated as the positive case rather than an early return. A bare
                // `return` at the top level of a classic script is a SyntaxError, and
                // it is thrown at parse time, so it took the whole file down with it —
                // pan, zoom and click-to-read included — rather than just skipping the
                // reveal it guarded.
                + "if(!rm&&('IntersectionObserver' in window)){"
                + "requestAnimationFrame(function(){requestAnimationFrame(function(){"
                // Only what is below the fold is ever made transparent. Anything already
                // on screen is left alone, so the report cannot open blank even if the
                // observer never fires.
                + "targets.forEach(function(el){"
                + "if(el.getBoundingClientRect().top>=window.innerHeight)el.classList.add('reveal');});"
                + "var io=new IntersectionObserver(function(es){es.forEach(function(en){"
                + "if(en.isIntersecting){show(en.target);io.unobserve(en.target);}});},"
                + "{rootMargin:'0px 0px -8% 0px',threshold:.05});"
                + "targets.forEach(function(el){if(el.classList.contains('reveal'))io.observe(el);});"
                // Failsafe. A report that never appears is far worse than one that
                // appears without the animation, so nothing stays hidden regardless
                // of whether the observer ever fires.
                + "setTimeout(function(){targets.forEach(show);},1200);});});}";
    }

    /**
     * A chart plus the readout that click-to-read writes into.
     *
     * <p>The readout is an aria-live region: without it a click announces nothing and
     * only sighted readers get the feature. The inner scroller lets a 1400-wide chart
     * keep a readable scale on a phone instead of being squashed to illegibility.</p>
     */
    private static String chartBlock(String svg) {
        String hint = "Click anywhere on the chart for the nearest point's exact value.";
        return "<div class=\"chartwrap\"><div class=\"chart-scroll\">" + svg + "</div>"
                + "<div class=\"readout\" role=\"status\" aria-live=\"polite\" "
                + "data-hint=\"" + hint + "\">" + hint + "</div></div>";
    }

    /**
     * Styling shared with the online viewer in {@code docs/index.html}.
     *
     * <p>Motion is all CSS transform and opacity, which the compositor handles
     * without a layout pass, and there are no libraries: the report has to open
     * straight off disk with no network, so a CDN animation library was never an
     * option. Everything is wrapped in a {@code prefers-reduced-motion} guard.</p>
     */
    private static String css() {
        return

                // One scale for space, type, depth and motion. Fluid rather than fixed:
                // a report gets opened on a phone as often as on the machine that wrote
                // it, and the floor of each clamp is what the phone gets.
                ":root{color-scheme:dark;"
                + "--bg:#14161a;--bg-elev:#191d24;--panel:#1e232b;--line:#2a2f37;--line-hi:#3d4550;"
                // --dim carries the readout's resting hint — the line that tells you
                // click-to-read exists at all — so it is held at 4.5:1 WCAG AA against
                // every background it sits on. The obvious dimmer grey came to 3.6:1.
                + "--text:#e8eaed;--muted:#9aa4b2;--dim:#828c99;--accent:#ffb454;--warn:#ffb454;"
                + "--t-xs:clamp(.72rem,.70rem + .10vw,.78rem);"
                + "--t-sm:clamp(.80rem,.77rem + .15vw,.88rem);"
                + "--t-base:clamp(.90rem,.86rem + .20vw,1rem);"
                + "--t-lg:clamp(1.05rem,.98rem + .35vw,1.25rem);"
                + "--t-xl:clamp(1.35rem,1.15rem + 1vw,2rem);"
                + "--t-2xl:clamp(1.75rem,1.40rem + 1.75vw,2.75rem);"
                + "--s-1:clamp(.25rem,.22rem + .15vw,.375rem);"
                + "--s-2:clamp(.5rem,.45rem + .25vw,.75rem);"
                + "--s-3:clamp(.75rem,.65rem + .5vw,1.125rem);"
                + "--s-4:clamp(1rem,.85rem + .75vw,1.5rem);"
                + "--s-6:clamp(1.5rem,1.25rem + 1.25vw,2.25rem);"
                + "--s-8:clamp(2rem,1.6rem + 2vw,3rem);"
                + "--r-sm:8px;--r-md:12px;--r-lg:16px;"
                + "--e1:0 1px 2px rgba(0,0,0,.35);--e2:0 4px 14px rgba(0,0,0,.38);"
                + "--ease:cubic-bezier(.22,.61,.36,1);--fast:130ms;--med:240ms;}"

                + "*{box-sizing:border-box;margin:0;}"
                + "html{-webkit-text-size-adjust:100%;}"
                + "body{font-family:ui-sans-serif,system-ui,Segoe UI,Roboto,Arial,sans-serif;"
                + "background:radial-gradient(1100px 560px at 50% -12%,rgba(64,80,110,.30),transparent 70%),"
                + "var(--bg);color:var(--text);font-size:var(--t-base);line-height:1.55;"
                + "-webkit-font-smoothing:antialiased;padding:var(--s-4);}"
                + "main{max-width:1180px;margin-inline:auto;}"

                // Identity first and largest: the question a reader opens a report with
                // is whose fight it was, and that used to be a line of body text.
                + ".hero{display:flex;align-items:center;gap:var(--s-4);flex-wrap:wrap;"
                + "padding:var(--s-4);margin-bottom:var(--s-4);"
                + "background:linear-gradient(160deg,var(--panel),var(--bg-elev));"
                + "border:1px solid var(--line);border-radius:var(--r-lg);box-shadow:var(--e2);}"
                + ".hero__avatar{width:clamp(56px,10vw,76px);height:clamp(56px,10vw,76px);flex:none;"
                + "image-rendering:pixelated;border-radius:var(--r-md);background:var(--bg-elev);"
                + "box-shadow:var(--e1);}"
                + ".hero__text{min-width:0;flex:1 1 16rem;}"
                + "h1{font-size:var(--t-2xl);line-height:1.15;letter-spacing:-.02em;font-weight:650;"
                + "overflow-wrap:anywhere;}"
                + ".hero__ign{font-size:var(--t-lg);font-weight:600;color:var(--accent);"
                + "letter-spacing:-.01em;overflow-wrap:anywhere;}"
                + ".vs{display:flex;align-items:center;gap:var(--s-2);flex-wrap:wrap;color:var(--muted);"
                + "font-size:var(--t-sm);margin-top:var(--s-2);}"
                + ".vs img{width:22px;height:22px;image-rendering:pixelated;border-radius:5px;"
                + "background:var(--bg-elev);vertical-align:middle;}"
                + ".vs__label{color:var(--dim);}"

                // Facts as discrete chips rather than one run-on sentence of middots.
                + ".meta{display:flex;gap:var(--s-2);flex-wrap:wrap;margin-top:var(--s-3);}"
                + ".chip{font-size:var(--t-xs);color:var(--muted);white-space:nowrap;padding:.28em .7em;"
                + "border:1px solid var(--line);border-radius:999px;background:rgba(255,255,255,.03);"
                + "font-variant-numeric:tabular-nums;}"

                + "section{margin-top:var(--s-8);}"
                + "h2{font-size:var(--t-lg);font-weight:600;letter-spacing:-.01em;display:flex;"
                + "align-items:baseline;gap:var(--s-2);margin-bottom:var(--s-3);}"
                + "h2::after{content:\"\";flex:1;height:1px;"
                + "background:linear-gradient(90deg,var(--line),transparent);}"
                + ".sub{color:var(--muted);font-size:var(--t-sm);margin-bottom:var(--s-3);}"
                + ".sub b{color:var(--text);font-weight:600;}"

                + "table{border-collapse:collapse;font-size:var(--t-sm);width:100%;"
                + "border:1px solid var(--line);border-radius:var(--r-md);overflow:hidden;}"
                + "td,th{border-bottom:1px solid var(--line);padding:var(--s-2) var(--s-3);text-align:left;}"
                + "tr:last-child td,tr:last-child th{border-bottom:0;}"
                + "th{background:var(--bg-elev);color:var(--muted);font-weight:600;white-space:nowrap;}"
                + "td{font-variant-numeric:tabular-nums;overflow-wrap:anywhere;}"
                + "tr{transition:background var(--fast) var(--ease);}tr:hover td{background:var(--bg-elev);}"

                // auto-fit rather than flex-wrap, so the cards share the width evenly
                // instead of leaving the last one stranded on a row of its own.
                + ".cards{display:grid;gap:var(--s-2);margin-bottom:var(--s-3);"
                + "grid-template-columns:repeat(auto-fit,minmax(clamp(6.5rem,18vw,8.5rem),1fr));}"
                + ".card{background:var(--bg-elev);border:1px solid var(--line);border-radius:var(--r-md);"
                + "padding:var(--s-3);box-shadow:var(--e1);"
                + "transition:transform var(--med) var(--ease),border-color var(--med) var(--ease),"
                + "box-shadow var(--med) var(--ease);}"
                + "@media (hover:hover){.card:hover{transform:translateY(-2px);border-color:var(--line-hi);"
                + "box-shadow:var(--e2);}}"
                + ".card .v{font-size:var(--t-xl);font-weight:650;letter-spacing:-.02em;line-height:1.1;"
                + "font-variant-numeric:tabular-nums;}"
                + ".card .k{font-size:var(--t-xs);color:var(--muted);margin-top:.15em;}"

                + ".intg{background:var(--bg-elev);border:1px solid var(--line);border-radius:var(--r-md);"
                + "padding:var(--s-4);font-family:ui-monospace,Consolas,monospace;font-size:var(--t-xs);"
                + "word-break:break-all;line-height:1.7;color:var(--muted);}"
                + ".warn{color:var(--warn);font-weight:600;}"

                // Points grow slightly under the cursor; the selected one keeps a ring.
                + "svg.chart circle{cursor:pointer;transition:r var(--fast) var(--ease),"
                + "stroke-width var(--fast) var(--ease);}"
                + "svg.chart circle:hover{stroke:#fff;stroke-width:1.5;r:4.5;}"
                + "svg.chart circle[data-sel]{stroke:#fff;stroke-width:2.5;r:5;}"
                + ".chartwrap{margin-bottom:var(--s-4);padding:var(--s-2);background:var(--bg-elev);"
                + "border:1px solid var(--line);border-radius:var(--r-lg);box-shadow:var(--e1);"
                + "transition:border-color var(--med) var(--ease),box-shadow var(--med) var(--ease);}"
                + "@media (hover:hover){.chartwrap:hover{border-color:var(--line-hi);box-shadow:var(--e2);}}"
                // No touch-action here. It used to be `none`, which suppresses the
                // browser's own panning — and pan/zoom binds mouse events only, so
                // nothing ever replaced the gesture it suppressed. On a phone that made
                // the scroller below unreachable and swallowed vertical page scrolling
                // over every chart. The browser owns touch.
                + "svg.chart{display:block;background:#161a20;border:1px solid var(--line);"
                + "border-radius:var(--r-md);cursor:grab;}"

                // The readout is an aria-live region, so it must not collapse when empty
                // or a screen reader announces a layout jump instead of a value.
                + ".readout{font-family:ui-monospace,Consolas,monospace;font-size:var(--t-xs);"
                + "color:var(--dim);padding:var(--s-2) var(--s-1) var(--s-1);min-height:2.2em;"
                + "transition:color var(--med) var(--ease);}"
                + ".readout.on{color:var(--text);animation:ctIn var(--med) var(--ease);}"
                + "@keyframes ctIn{from{opacity:0;transform:translateY(3px);}to{opacity:1;transform:none;}}"

                + ".reveal{opacity:0;transform:translateY(12px);"
                + "transition:opacity 420ms var(--ease),transform 420ms var(--ease);}"
                + ".reveal.shown{opacity:1;transform:none;}"
                + "details{margin-top:var(--s-2);}"
                + "summary{cursor:pointer;color:var(--muted);font-size:var(--t-sm);"
                + "transition:color var(--fast) var(--ease);}"
                + "summary:hover{color:var(--text);}"
                + "pre{white-space:pre-wrap;word-break:break-all;background:#0f1114;padding:var(--s-3);"
                + "border-radius:var(--r-sm);font-size:var(--t-xs);border:1px solid var(--line);"
                + "margin-top:var(--s-2);}"
                + ":focus-visible{outline:2px solid var(--accent);outline-offset:3px;border-radius:6px;}"

                // Anyone who has asked the system for less motion gets none of it.
                + "@media (prefers-reduced-motion:reduce){*,*::before,*::after{"
                + "animation-duration:.01ms!important;animation-iteration-count:1!important;"
                + "transition-duration:.01ms!important;}.reveal{opacity:1;transform:none;}}"

                // Charts carry millisecond detail that does not survive being squeezed
                // onto a phone, so below this width they scroll sideways at a readable
                // size instead of shrinking to illegibility. The width is W, the charts'
                // own design width, not a smaller round number: the axis text is sized
                // in user units, so anything less scales it down with everything else.
                // At 680px it came out at 4.9 CSS px — scrolling for labels still too
                // small to read, which is the worst of both. 1:1 is the whole point.
                + "@media (max-width:640px){.chart-scroll{overflow-x:auto;overscroll-behavior-x:contain;}"
                + ".chart-scroll svg.chart:not(.chart--fit){min-width:" + W + "px;}}";
    }

    // ── Formatting ───────────────────────────────────────────────────────────

    private static void card(StringBuilder s, String value, String key) {
        s.append("<div class=\"card\"><div class=\"v\">").append(value).append("</div><div class=\"k\">")
                .append(key).append("</div></div>");
    }

    private static String offset(long ms) {
        return "+" + (ms / 1000) + "." + String.format(Locale.ROOT, "%03d", Math.abs(ms % 1000)) + "s";
    }

    /** Label with just enough decimals for the step to read distinctly. */
    private static String tick(double v, double step) {
        if (step >= 1.0) {
            return Long.toString(Math.round(v));
        }
        return step >= 0.1 ? String.format(Locale.ROOT, "%.1f", v) : String.format(Locale.ROOT, "%.2f", v);
    }

    private static String hex(int rgb) {
        return String.format(Locale.ROOT, "#%06x", rgb & 0xFFFFFF);
    }

    /**
     * A coordinate for an SVG geometry attribute.
     *
     * <p>{@code Locale.ROOT} is not decoration here. The default overload formats
     * with the default locale, so on any comma-decimal machine — most of Europe and
     * Brazil — this returned {@code "12,3"}, which is not a number an SVG attribute
     * can hold. Every point in the aim scatter is positioned through this, so the
     * whole chart collapsed for those users and rendered fine for everyone who
     * tested it. The label formatters below take it too, for the same reason and so
     * the report reads identically to the viewer's {@code toFixed()}.</p>
     */
    private static String r(double v) {
        return String.format(Locale.ROOT, "%.1f", v);
    }

    static String fmt(double v) {
        return String.format(Locale.ROOT, "%.2f", v);
    }

    static String esc(String in) {
        if (in == null) {
            return "";
        }
        return in.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;");
    }
}
