package combat_tracker.record;

import java.util.List;

/**
 * Renders a {@link SessionData} into the self-contained HTML report.
 *
 * <p>No Minecraft imports on purpose — see {@link SessionData}. Everything here is
 * string building and arithmetic, so {@link ReportPreview} can render a synthetic
 * session and prove the charts are right without starting the game.</p>
 */
public final class ReportBuilder {
    /** Vanilla melee range, drawn as a reference line on the reach chart. */
    private static final double VANILLA_REACH = 3.0;
    /** Standing player hitbox, drawn to scale on the aim scatter. */
    private static final double HITBOX_HALF_W = 0.3;
    private static final double HITBOX_HALF_H = 0.9;

    private static final int HIT_COLOR = 0x4caf50;
    private static final int MISS_COLOR = 0xef5350;
    private static final int COMBO_COLOR = 0x29b6f6;

    private ReportBuilder() {
    }

    public static String build(SessionData d, String sha, String sig, String canonical) {
        StringBuilder s = new StringBuilder(16384);
        s.append("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        s.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        s.append("<title>Combat Tracker session ").append(esc(d.startUtc)).append("</title><style>");
        s.append(css());
        s.append("</style></head><body>");

        s.append("<h1>Combat Tracker Session Report</h1>");
        s.append("<div class=\"sub\">Player <b>").append(esc(d.player)).append("</b> &middot; ")
                .append(esc(d.mod)).append(" on MC ").append(esc(d.mcVersion)).append("</div>");
        s.append("<div class=\"sub\">Charts: <b>click a point for its exact value</b> &middot; scroll to zoom "
                + "&middot; drag to pan &middot; double-click to reset.</div>");

        header(s, d);
        jumpSection(s, d);
        comboSection(s, d);
        reachSection(s, d);
        aimSection(s, d);
        integritySection(s, sha, sig, canonical);

        s.append("<p class=\"sub\">Generated by Combat Tracker. Charts are SVG embedded in this file.</p>");
        s.append("<script>").append(chartScript()).append("</script>");
        s.append("</body></html>");
        return s.toString();
    }

    // ── Sections ─────────────────────────────────────────────────────────────

    private static void header(StringBuilder s, SessionData d) {
        s.append("<table><tr><th>Start (time signature)</th><td>").append(esc(d.startUtc))
                .append(" <span class=\"sub\">(epoch ").append(d.startEpochMs).append(")</span></td></tr>");
        s.append("<tr><th>End (time signature)</th><td>").append(esc(d.endUtc))
                .append(" <span class=\"sub\">(epoch ").append(d.endEpochMs).append(")</span></td></tr>");
        long durS = Math.max(0, (d.endEpochMs - d.startEpochMs) / 1000);
        s.append("<tr><th>Duration</th><td>").append(durS / 60).append("m ").append(durS % 60).append("s</td></tr>");
        s.append("<tr><th>Player UUID</th><td>").append(esc(d.playerUuid)).append("</td></tr>");
        s.append("<tr><th>Ping (session average)</th><td>").append(Math.round(d.pingMs))
                .append(" ms <span class=\"sub\">(recorded for context; it adjusts no measurement)</span></td></tr>");
        if (!d.opponents.isEmpty()) {
            s.append("<tr><th>Opponents</th><td>").append(esc(String.join(", ", d.opponents))).append("</td></tr>");
        }
        s.append("</table>");
    }

    private static void jumpSection(StringBuilder s, SessionData d) {
        s.append("<h2>Jump resets</h2><div class=\"cards\">");
        card(s, Integer.toString(d.jumpAttempts), "attempts");
        card(s, Integer.toString(d.jumpHits), "hits");
        card(s, Integer.toString(d.jumpMisses), "misses");
        card(s, fmt(d.jumpAvgMs) + " ms", "avg delta");
        card(s, fmt(d.jumpSdMs) + " ms", "std dev");
        s.append("</div>");
        s.append(chartBlock(timeChart("Jump-reset delta over time (ms)", d.jumpEvents, d.startEpochMs, d.endEpochMs)));
    }

    private static void comboSection(StringBuilder s, SessionData d) {
        s.append("<h2>Combo timing</h2><div class=\"cards\">");
        card(s, Integer.toString(d.combos), "combos");
        card(s, Integer.toString(d.comboIntervals), "intervals");
        card(s, fmt(d.comboAvgMs) + " ms", "avg interval");
        card(s, fmt(d.comboJitterMs) + " ms", "jitter (SD)");
        s.append("</div>");
        s.append(chartBlock(comboChart(d)));
    }

    private static void reachSection(StringBuilder s, SessionData d) {
        s.append("<h2>Reach</h2><div class=\"cards\">");
        card(s, Integer.toString(d.swings), "swings");
        card(s, Integer.toString(d.swingHits), "landed");
        card(s, Integer.toString(d.swingMisses), "whiffed");
        card(s, fmt(d.reachAvgBlocks) + " b", "avg reach");
        card(s, fmt(d.reachMaxBlocks) + " b", "max reach");
        card(s, fmt(d.reachSdBlocks) + " b", "std dev");
        s.append("</div>");
        s.append("<div class=\"sub\">Green landed, red whiffed. Dashed line is vanilla melee range.</div>");
        s.append(chartBlock(reachChart(d)));
    }

    private static void aimSection(StringBuilder s, SessionData d) {
        s.append("<h2>Aim placement</h2><div class=\"cards\">");
        card(s, fmt(d.aimAvgDeg) + "&deg;", "avg off-centre");
        card(s, fmt(d.aimSdDeg) + "&deg;", "std dev");
        s.append("</div>");
        s.append("<div class=\"sub\">Hitbox drawn to scale. Green landed, red whiffed.</div>");
        s.append(chartBlock(aimScatter(d)));
    }

    private static void integritySection(StringBuilder s, String sha, String sig, String canonical) {
        s.append("<h2>Integrity</h2><div class=\"intg\">");
        s.append("Algorithm: SHA-256 + HMAC-SHA256<br>SHA-256: ").append(esc(sha))
                .append("<br>Signature: ").append(esc(sig));
        s.append("<br><span class=\"warn\">Note:</span> the signing key ships inside the open-source mod, so this "
                + "detects casual edits but is <b>not</b> unforgeable. Verify by recomputing SHA-256 over the exact "
                + "canonicalData string below (UTF-8).");
        s.append("<br><br><span class=\"warn\">On reach and aim:</span> measured on your own client, where other "
                + "players are interpolated locally, so these will not match a server-side anti-cheat exactly.</div>");
        s.append("<details><summary>Canonical data (hashed bytes)</summary><pre>")
                .append(esc(canonical)).append("</pre></details>");
    }

    // ── Charts ───────────────────────────────────────────────────────────────

    private static final int W = 1400;
    private static final int H = 300;
    private static final int ML = 48;
    private static final int MR = 16;
    private static final int MT = 28;
    private static final int MB = 30;

    private static String timeChart(String title, List<SessionData.JEvent> pts, long startMs, long endMs) {
        StringBuilder s = svgOpen(W, H);
        title(s, title);
        if (pts.isEmpty()) {
            return noData(s);
        }
        double yMin = 0, yMax = 1;
        for (SessionData.JEvent p : pts) {
            yMax = Math.max(yMax, p.deltaMs);
            yMin = Math.min(yMin, p.deltaMs);
        }
        yMax = yMax * 1.1 + 1;
        long span = Math.max(1, endMs - startMs);
        axes(s, yMin, yMax, "ms");

        int pw = W - ML - MR, ph = H - MT - MB;
        StringBuilder poly = new StringBuilder();
        StringBuilder dots = new StringBuilder();
        for (SessionData.JEvent p : pts) {
            int x = (int) (ML + (double) (p.t - startMs) / span * pw);
            int y = (int) (MT + ph - (p.deltaMs - yMin) / (yMax - yMin) * ph);
            poly.append(x).append(",").append(y).append(" ");
            boolean ok = "SUCCESS".equals(p.result);
            String tip = offset(p.t - startMs) + " : " + p.deltaMs + " ms"
                    + (p.result != null ? " (" + p.result + ")" : "");
            dot(dots, x, y, ok ? HIT_COLOR : MISS_COLOR, tip);
        }
        s.append("<polyline points=\"").append(poly.toString().trim())
                .append("\" fill=\"none\" stroke=\"#4caf50\" stroke-opacity=\"0.35\" stroke-width=\"1\"/>");
        s.append(dots).append("</svg>");
        return s.toString();
    }

    private static String comboChart(SessionData d) {
        StringBuilder s = svgOpen(W, H);
        title(s, "Combo inter-hit interval over time (ms)");
        if (d.comboEvents.isEmpty()) {
            return noData(s);
        }
        double yMin = 0, yMax = 1;
        for (SessionData.CEvent c : d.comboEvents) {
            yMax = Math.max(yMax, c.intervalMs);
        }
        yMax = yMax * 1.1 + 1;
        long span = Math.max(1, d.endEpochMs - d.startEpochMs);
        axes(s, yMin, yMax, "ms");

        int pw = W - ML - MR, ph = H - MT - MB;
        StringBuilder poly = new StringBuilder();
        StringBuilder dots = new StringBuilder();
        for (SessionData.CEvent c : d.comboEvents) {
            int x = (int) (ML + (double) (c.t - d.startEpochMs) / span * pw);
            int y = (int) (MT + ph - (c.intervalMs - yMin) / (yMax - yMin) * ph);
            poly.append(x).append(",").append(y).append(" ");
            dot(dots, x, y, COMBO_COLOR, offset(c.t - d.startEpochMs) + " : " + c.intervalMs + " ms");
        }
        s.append("<polyline points=\"").append(poly.toString().trim())
                .append("\" fill=\"none\" stroke=\"#29b6f6\" stroke-opacity=\"0.5\" stroke-width=\"1\"/>");
        s.append(dots).append("</svg>");
        return s.toString();
    }

    private static String reachChart(SessionData d) {
        StringBuilder s = svgOpen(W, H);
        title(s, "Reach per swing (blocks)");
        if (d.swingEvents.isEmpty()) {
            return noData(s);
        }
        double yMax = VANILLA_REACH;
        for (SessionData.SEvent e : d.swingEvents) {
            yMax = Math.max(yMax, e.reach);
        }
        yMax = yMax * 1.15;
        long span = Math.max(1, d.endEpochMs - d.startEpochMs);
        axes(s, 0, yMax, "blocks");

        int pw = W - ML - MR, ph = H - MT - MB;

        // Vanilla-range reference line.
        int refY = (int) (MT + ph - VANILLA_REACH / yMax * ph);
        s.append("<line x1=\"").append(ML).append("\" y1=\"").append(refY).append("\" x2=\"").append(ML + pw)
                .append("\" y2=\"").append(refY)
                .append("\" stroke=\"#ffb454\" stroke-width=\"1\" stroke-dasharray=\"4 4\"/>");
        s.append("<text x=\"").append(ML + pw).append("\" y=\"").append(refY - 4)
                .append("\" fill=\"#ffb454\" font-size=\"10\" text-anchor=\"end\" font-family=\"sans-serif\">")
                .append("vanilla 3.0</text>");

        StringBuilder dots = new StringBuilder();
        for (SessionData.SEvent e : d.swingEvents) {
            int x = (int) (ML + (double) (e.t - d.startEpochMs) / span * pw);
            int y = (int) (MT + ph - e.reach / yMax * ph);
            String who = e.target >= 0 && e.target < d.opponents.size() ? " vs " + d.opponents.get(e.target) : "";
            dot(dots, x, y, e.hit ? HIT_COLOR : MISS_COLOR,
                    offset(e.t - d.startEpochMs) + " : " + fmt(e.reach) + " blocks "
                            + (e.hit ? "(landed)" : "(whiffed)") + who);
        }
        s.append(dots).append("</svg>");
        return s.toString();
    }

    /**
     * Scatter of aim offsets with the hitbox drawn to scale. Both axes share one
     * scale so the box keeps its real 0.6 x 1.8 proportions — squashing it to fill
     * the frame would make centred aim look more spread out than it is.
     */
    private static String aimScatter(SessionData d) {
        int w = 420, h = 460, ml = 44, mr = 16, mt = 28, mb = 34;
        int pw = w - ml - mr, ph = h - mt - mb;
        StringBuilder s = svgOpen(w, h, 520);
        title(s, "Aim offset from hitbox centre (blocks)");
        if (d.swingEvents.isEmpty()) {
            return noData(s, w, h);
        }

        double halfW = HITBOX_HALF_W * 1.6;
        double halfH = HITBOX_HALF_H * 1.25;
        for (SessionData.SEvent e : d.swingEvents) {
            halfW = Math.max(halfW, Math.abs(e.offX) * 1.1);
            halfH = Math.max(halfH, Math.abs(e.offY) * 1.1);
        }
        // One scale for both axes keeps the hitbox honest.
        double scale = Math.min(pw / (2 * halfW), ph / (2 * halfH));
        double cx = ml + pw / 2.0;
        double cy = mt + ph / 2.0;

        // Hitbox outline.
        double bw = HITBOX_HALF_W * scale, bh = HITBOX_HALF_H * scale;
        s.append("<rect x=\"").append(r(cx - bw)).append("\" y=\"").append(r(cy - bh))
                .append("\" width=\"").append(r(bw * 2)).append("\" height=\"").append(r(bh * 2))
                .append("\" fill=\"#4caf50\" fill-opacity=\"0.06\" stroke=\"#4a5561\" stroke-width=\"1\"/>");
        // Centre crosshair.
        s.append("<line x1=\"").append(r(cx)).append("\" y1=\"").append(mt).append("\" x2=\"").append(r(cx))
                .append("\" y2=\"").append(mt + ph).append("\" stroke=\"#2a2f37\"/>");
        s.append("<line x1=\"").append(ml).append("\" y1=\"").append(r(cy)).append("\" x2=\"").append(ml + pw)
                .append("\" y2=\"").append(r(cy)).append("\" stroke=\"#2a2f37\"/>");

        StringBuilder dots = new StringBuilder();
        for (SessionData.SEvent e : d.swingEvents) {
            double x = cx + e.offX * scale;
            double y = cy - e.offY * scale;
            String who = e.target >= 0 && e.target < d.opponents.size() ? " vs " + d.opponents.get(e.target) : "";
            dots.append("<circle cx=\"").append(r(x)).append("\" cy=\"").append(r(y))
                    .append("\" r=\"3\" fill=\"").append(hex(e.hit ? HIT_COLOR : MISS_COLOR))
                    .append("\" fill-opacity=\"0.75\"><title>")
                    .append(esc(fmt(e.offX) + ", " + fmt(e.offY) + " blocks / " + fmt(e.aimDeg) + " deg" + who))
                    .append("</title></circle>");
        }
        s.append(dots);
        s.append("<text x=\"").append(ml).append("\" y=\"").append(h - 10)
                .append("\" fill=\"#6b7480\" font-size=\"10\" font-family=\"sans-serif\">")
                .append("box = player hitbox to scale &middot; green landed, red whiffed</text>");
        s.append("</svg>");
        return s.toString();
    }

    // ── SVG helpers ──────────────────────────────────────────────────────────

    private static StringBuilder svgOpen(int w, int h) {
        return svgOpen(w, h, null);
    }

    /**
     * @param maxWidthPx cap in CSS pixels, or null to fill the available width.
     *                   The scatter is squarish and looks wrong stretched; the
     *                   time-series charts are better the wider they get.
     */
    private static StringBuilder svgOpen(int w, int h, Integer maxWidthPx) {
        StringBuilder s = new StringBuilder(2048);
        s.append("<svg class=\"chart\" viewBox=\"0 0 ").append(w).append(" ").append(h)
                .append("\" width=\"100%\" style=\"")
                .append(maxWidthPx == null ? "" : "max-width:" + maxWidthPx + "px;")
                .append("background:#161a20;border:1px solid #2a2f37;border-radius:8px;cursor:grab;")
                .append("touch-action:none;\">");
        return s;
    }

    private static void title(StringBuilder s, String text) {
        s.append("<text x=\"").append(ML).append("\" y=\"18\" fill=\"#9fb3c8\" font-size=\"13\" ")
                .append("font-family=\"sans-serif\">").append(esc(text)).append("</text>");
    }

    private static String noData(StringBuilder s) {
        return noData(s, W, H);
    }

    private static String noData(StringBuilder s, int w, int h) {
        s.append("<text x=\"").append(w / 2).append("\" y=\"").append(h / 2)
                .append("\" fill=\"#5f6772\" font-size=\"13\" text-anchor=\"middle\" ")
                .append("font-family=\"sans-serif\">no data recorded</text></svg>");
        return s.toString();
    }

    /**
     * Y axis with gridlines on round values.
     *
     * <p>The old version drew exactly three lines at min/mid/max, which on a
     * millisecond axis produced labels like "37" and left a reader guessing at
     * everything between them. Milliseconds are the whole point of these charts,
     * so this picks a round step (1, 2, 2.5, 5, 10, ...) sized to the range and
     * labels every line.</p>
     */
    private static void axes(StringBuilder s, double yMin, double yMax, String unit) {
        int pw = W - ML - MR, ph = H - MT - MB;
        s.append("<line x1=\"").append(ML).append("\" y1=\"").append(MT).append("\" x2=\"").append(ML)
                .append("\" y2=\"").append(MT + ph).append("\" stroke=\"#2a2f37\"/>");
        s.append("<line x1=\"").append(ML).append("\" y1=\"").append(MT + ph).append("\" x2=\"").append(ML + pw)
                .append("\" y2=\"").append(MT + ph).append("\" stroke=\"#2a2f37\"/>");

        double step = niceStep(yMax - yMin, 6);
        double first = Math.ceil(yMin / step) * step;
        for (double val = first; val <= yMax + step * 0.001; val += step) {
            int yy = (int) (MT + ph - (val - yMin) / (yMax - yMin) * ph);
            if (yy < MT || yy > MT + ph) {
                continue;
            }
            boolean zero = Math.abs(val) < step * 0.001;
            s.append("<line x1=\"").append(ML - 3).append("\" y1=\"").append(yy).append("\" x2=\"").append(ML + pw)
                    .append("\" y2=\"").append(yy).append("\" stroke=\"").append(zero ? "#3a424d" : "#21262e")
                    .append("\"/>");
            s.append("<text x=\"").append(ML - 6).append("\" y=\"").append(yy + 3)
                    .append("\" fill=\"#6b7480\" font-size=\"10\" text-anchor=\"end\" font-family=\"sans-serif\">")
                    .append(tick(val, step)).append("</text>");
        }
        if (unit != null) {
            s.append("<text x=\"").append(ML - 6).append("\" y=\"").append(MT - 8)
                    .append("\" fill=\"#4a5561\" font-size=\"9\" text-anchor=\"end\" font-family=\"sans-serif\">")
                    .append(esc(unit)).append("</text>");
        }
    }

    /** Rounds a raw axis step up to the nearest 1 / 2 / 2.5 / 5 / 10 x power of ten. */
    private static double niceStep(double range, int targetLines) {
        double raw = Math.max(1.0e-9, range / Math.max(1, targetLines));
        double mag = Math.pow(10, Math.floor(Math.log10(raw)));
        double norm = raw / mag;
        double step;
        if (norm <= 1.0) {
            step = 1.0;
        } else if (norm <= 2.0) {
            step = 2.0;
        } else if (norm <= 2.5) {
            step = 2.5;
        } else if (norm <= 5.0) {
            step = 5.0;
        } else {
            step = 10.0;
        }
        return step * mag;
    }

    private static void dot(StringBuilder s, int x, int y, int color, String tip) {
        s.append("<circle cx=\"").append(x).append("\" cy=\"").append(y).append("\" r=\"3\" fill=\"")
                .append(hex(color)).append("\"><title>").append(esc(tip)).append("</title></circle>");
    }

    /**
     * Pan, zoom, and click-to-read. Shared verbatim with the online viewer in
     * {@code docs/index.html} — if you change one, change the other.
     *
     * <p>A click selects the <em>nearest</em> point rather than requiring a direct
     * hit on it: the dots are three pixels across, and on a dense chart hitting one
     * exactly is not realistic. The search radius is scaled by the current zoom so
     * it stays constant on screen.</p>
     *
     * <p>Drags are excluded by distance travelled, otherwise every pan would end by
     * selecting whatever happened to be under the cursor.</p>
     */
    private static String chartScript() {
        return "document.querySelectorAll('svg.chart').forEach(function(svg){"
                + "var vb=svg.getAttribute('viewBox').split(' ').map(Number);var init=vb.slice();"
                + "var v={x:vb[0],y:vb[1],w:vb[2],h:vb[3]};"
                + "function ap(){svg.setAttribute('viewBox',v.x+' '+v.y+' '+v.w+' '+v.h);}"
                + "var out=svg.parentNode.querySelector('.readout');var sel=null;"
                + "function clear(){if(sel){sel.removeAttribute('data-sel');sel=null;}"
                + "if(out){out.textContent=out.getAttribute('data-hint');out.classList.remove('on');}}"
                + "function pick(c){if(sel)sel.removeAttribute('data-sel');sel=c;c.setAttribute('data-sel','1');"
                + "if(out){var t=c.querySelector('title');out.textContent=t?t.textContent:'';out.classList.add('on');}}"
                + "svg.addEventListener('wheel',function(e){e.preventDefault();var r=svg.getBoundingClientRect();"
                + "var mx=v.x+(e.clientX-r.left)/r.width*v.w;var my=v.y+(e.clientY-r.top)/r.height*v.h;"
                + "var f=e.deltaY<0?0.85:1/0.85;v.w*=f;v.h*=f;"
                + "v.x=mx-(e.clientX-r.left)/r.width*v.w;v.y=my-(e.clientY-r.top)/r.height*v.h;ap();},{passive:false});"
                + "var d=false,lx=0,ly=0,moved=0;"
                + "svg.addEventListener('mousedown',function(e){d=true;lx=e.clientX;ly=e.clientY;moved=0;"
                + "svg.style.cursor='grabbing';});"
                + "window.addEventListener('mousemove',function(e){if(!d)return;"
                + "moved+=Math.abs(e.clientX-lx)+Math.abs(e.clientY-ly);var r=svg.getBoundingClientRect();"
                + "v.x-=(e.clientX-lx)/r.width*v.w;v.y-=(e.clientY-ly)/r.height*v.h;lx=e.clientX;ly=e.clientY;ap();});"
                + "window.addEventListener('mouseup',function(){d=false;svg.style.cursor='grab';});"
                + "svg.addEventListener('click',function(e){"
                + "if(moved>4)return;"                     // that was a pan, not a click
                + "var r=svg.getBoundingClientRect();"
                + "var ux=v.x+(e.clientX-r.left)/r.width*v.w;var uy=v.y+(e.clientY-r.top)/r.height*v.h;"
                + "var best=null,bd=Infinity;"
                + "svg.querySelectorAll('circle').forEach(function(c){"
                + "var dx=+c.getAttribute('cx')-ux,dy=+c.getAttribute('cy')-uy;var dd=dx*dx+dy*dy;"
                + "if(dd<bd){bd=dd;best=c;}});"
                + "var lim=14*(v.w/init[2]);"              // constant on screen as you zoom
                + "if(best&&bd<=lim*lim)pick(best);else clear();});"
                + "function ease(a,b,t){return a+(b-a)*t;}"
                + "svg.addEventListener('dblclick',function(){"
                + "if(window.matchMedia&&window.matchMedia('(prefers-reduced-motion:reduce)').matches){"
                + "v={x:init[0],y:init[1],w:init[2],h:init[3]};ap();clear();return;}"
                + "var f={x:v.x,y:v.y,w:v.w,h:v.h},t0=performance.now();"
                + "(function step(now){var k=Math.min(1,(now-t0)/260);"
                + "var e=1-Math.pow(1-k,3);"                       // ease-out cubic
                + "v.x=ease(f.x,init[0],e);v.y=ease(f.y,init[1],e);"
                + "v.w=ease(f.w,init[2],e);v.h=ease(f.h,init[3],e);ap();"
                + "if(k<1)requestAnimationFrame(step);})(t0);clear();});"
                + "});"
                + "var rm=window.matchMedia&&window.matchMedia('(prefers-reduced-motion:reduce)').matches;"
                + "var targets=[].slice.call(document.querySelectorAll('h2,.cards,.chartwrap,table,.intg'));"
                + "function show(el){el.classList.add('shown');}"
                + "if(rm||!('IntersectionObserver' in window)){"
                + "return;}else{requestAnimationFrame(function(){requestAnimationFrame(function(){"
                // Only what is below the fold is ever made transparent. Anything already
                // on screen is left alone, so the report cannot open blank even if the
                // observer never fires.
                + "targets.forEach(function(el){"
                + "if(el.getBoundingClientRect().top>=window.innerHeight)el.classList.add('reveal');});"
                + "var io=new IntersectionObserver(function(es){es.forEach(function(en){"
                + "if(en.isIntersecting){show(en.target);io.unobserve(en.target);}});},"
                + "{rootMargin:'0px 0px -8% 0px',threshold:.05});"
                + "targets.forEach(function(el){if(el.classList.contains('reveal'))io.observe(el);});"
                // Failsafe. A report that never appears is far worse than one that
                // appears without the animation, so nothing stays hidden regardless
                // of whether the observer ever fires.
                + "setTimeout(function(){targets.forEach(show);},1200);});});}";
    }

    /** Wraps a chart with the readout line that click-to-read writes into. */
    private static String chartBlock(String svg) {
        String hint = "Click anywhere on the chart for the nearest point's exact value.";
        return "<div class=\"chartwrap\">" + svg
                + "<div class=\"readout\" data-hint=\"" + hint + "\">" + hint + "</div></div>";
    }

    /**
     * Styling shared with the online viewer in {@code docs/index.html}.
     *
     * <p>Motion is all CSS transform and opacity, which the compositor handles
     * without a layout pass, and there are no libraries: the report has to open
     * straight off disk with no network, so a CDN animation library was never an
     * option. Everything is wrapped in a {@code prefers-reduced-motion} guard.</p>
     */
    private static String css() {
        return ":root{--bg:#14161a;--panel:#1c2026;--panel-2:#161a20;--line:#2a2f37;--line-hi:#3d4550;"
                + "--text:#e8eaed;--muted:#8a93a0;--dim:#5f6772;--accent:#9fb3c8;--warn:#ffb454;"
                + "--ease:cubic-bezier(.22,.61,.36,1);--fast:140ms;--med:220ms;"
                + "--e1:0 1px 3px rgba(0,0,0,.30);--e2:0 6px 18px rgba(0,0,0,.38);}"
                + "*{box-sizing:border-box;}"
                + "body{font-family:system-ui,Segoe UI,Arial,sans-serif;background:var(--bg);color:var(--text);"
                + "margin:0;padding:clamp(16px,2.5vw,32px);-webkit-font-smoothing:antialiased;}"
                + "h1{font-size:clamp(19px,1.4vw+14px,26px);margin:0 0 4px;letter-spacing:-.01em;}"
                + "h2{font-size:clamp(14px,.5vw+12px,17px);margin:28px 0 8px;color:var(--accent);"
                + "letter-spacing:.01em;}"
                + ".sub{color:var(--muted);font-size:13px;margin-bottom:12px;line-height:1.55;}"
                + "table{border-collapse:collapse;font-size:13px;margin:4px 0;}"
                + "td,th{border:1px solid var(--line);padding:5px 11px;text-align:left;}"
                + "th{background:var(--panel);color:var(--accent);font-weight:600;}"
                + "tr{transition:background var(--fast) var(--ease);}tr:hover td{background:#191d24;}"
                + ".cards{display:flex;flex-wrap:wrap;gap:12px;margin:10px 0;}"
                + ".card{background:var(--panel);border:1px solid var(--line);border-radius:10px;"
                + "padding:11px 17px;min-width:112px;box-shadow:var(--e1);"
                + "transition:transform var(--med) var(--ease),border-color var(--med) var(--ease),"
                + "box-shadow var(--med) var(--ease);}"
                + ".card:hover{transform:translateY(-2px);border-color:var(--line-hi);box-shadow:var(--e2);}"
                + ".card .v{font-size:clamp(19px,1vw+15px,23px);font-weight:600;letter-spacing:-.01em;}"
                + ".card .k{font-size:12px;color:var(--muted);margin-top:1px;}"
                + ".intg{background:var(--panel-2);border:1px solid var(--line);border-radius:10px;padding:13px;"
                + "font-family:ui-monospace,Consolas,monospace;font-size:12px;word-break:break-all;line-height:1.6;}"
                + ".warn{color:var(--warn);}"
                // Points: grow slightly under the cursor, and the selected one keeps a ring.
                + "svg.chart circle{cursor:pointer;transition:r var(--fast) var(--ease),"
                + "stroke-width var(--fast) var(--ease);}"
                + "svg.chart circle:hover{stroke:#fff;stroke-width:1.5;r:4.5;}"
                + "svg.chart circle[data-sel]{stroke:#fff;stroke-width:2.5;r:5;}"
                + ".chartwrap{margin-bottom:16px;}"
                + "svg.chart{box-shadow:var(--e1);transition:border-color var(--med) var(--ease),"
                + "box-shadow var(--med) var(--ease);}"
                + ".chartwrap:hover svg.chart{border-color:var(--line-hi);box-shadow:var(--e2);}"
                + ".readout{font-family:ui-monospace,Consolas,monospace;font-size:12px;color:var(--dim);"
                + "padding:7px 2px 0;min-height:18px;transition:color var(--med) var(--ease);}"
                + ".readout.on{color:var(--text);}"
                // The value swap gets a short lift so a changed reading is noticeable.
                + "@keyframes ctIn{from{opacity:0;transform:translateY(3px);}to{opacity:1;transform:none;}}"
                + ".readout.on{animation:ctIn var(--med) var(--ease);}"
                // Sections fade up once as they scroll in.
                + ".reveal{opacity:0;transform:translateY(14px);"
                + "transition:opacity 460ms var(--ease),transform 460ms var(--ease);}"
                + ".reveal.shown{opacity:1;transform:none;}"
                + "details{margin-top:8px;}summary{cursor:pointer;transition:color var(--fast) var(--ease);}"
                + "summary:hover{color:var(--accent);}"
                + "pre{white-space:pre-wrap;word-break:break-all;background:#0f1114;padding:11px;"
                + "border-radius:8px;font-size:11px;border:1px solid var(--line);}"
                + ":focus-visible{outline:2px solid var(--accent);outline-offset:2px;border-radius:4px;}"
                // Anyone who has asked the system for less motion gets none of it.
                + "@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important;}"
                + ".reveal{opacity:1;}}";
    }

    // ── Formatting ───────────────────────────────────────────────────────────

    private static void card(StringBuilder s, String value, String key) {
        s.append("<div class=\"card\"><div class=\"v\">").append(value).append("</div><div class=\"k\">")
                .append(key).append("</div></div>");
    }

    private static String offset(long ms) {
        return "+" + (ms / 1000) + "." + String.format("%03d", Math.abs(ms % 1000)) + "s";
    }

    /** Label with just enough decimals for the step to read distinctly. */
    private static String tick(double v, double step) {
        if (step >= 1.0) {
            return Long.toString(Math.round(v));
        }
        return step >= 0.1 ? String.format("%.1f", v) : String.format("%.2f", v);
    }

    private static String hex(int rgb) {
        return String.format("#%06x", rgb & 0xFFFFFF);
    }

    private static String r(double v) {
        return String.format("%.1f", v);
    }

    static String fmt(double v) {
        return String.format("%.2f", v);
    }

    static String esc(String in) {
        if (in == null) {
            return "";
        }
        return in.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;");
    }
}
