package combat_tracker.record;

import java.util.List;

/**
 * Renders a {@link SessionData} into the self-contained HTML report.
 *
 * <p>No Minecraft imports on purpose — see {@link SessionData}. Everything here is
 * string building and arithmetic, so {@link ReportPreview} can render a synthetic
 * session and prove the charts are right without starting the game.</p>
 */
public final class ReportBuilder {
    /** Vanilla melee range, drawn as a reference line on the reach chart. */
    private static final double VANILLA_REACH = 3.0;
    /** Standing player hitbox, drawn to scale on the aim scatter. */
    private static final double HITBOX_HALF_W = 0.3;
    private static final double HITBOX_HALF_H = 0.9;

    private static final int HIT_COLOR = 0x4caf50;
    private static final int MISS_COLOR = 0xef5350;
    private static final int COMBO_COLOR = 0x29b6f6;

    private ReportBuilder() {
    }

    public static String build(SessionData d, String sha, String sig, String canonical) {
        StringBuilder s = new StringBuilder(16384);
        s.append("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        s.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        s.append("<title>Combat Tracker session ").append(esc(d.startUtc)).append("</title><style>");
        s.append(css());
        s.append("</style></head><body>");

        s.append("<h1>Combat Tracker &mdash; Session Report</h1>");
        s.append("<div class=\"sub\">Player <b>").append(esc(d.player)).append("</b> &middot; ")
                .append(esc(d.mod)).append(" on MC ").append(esc(d.mcVersion)).append("</div>");
        s.append("<div class=\"sub\">Charts: scroll to zoom &middot; drag to pan &middot; double-click to reset.</div>");

        header(s, d);
        jumpSection(s, d);
        comboSection(s, d);
        reachSection(s, d);
        aimSection(s, d);
        integritySection(s, sha, sig, canonical);

        s.append("<p class=\"sub\">Generated by Combat Tracker. Charts are SVG embedded in this file.</p>");
        s.append("<script>").append(panZoomScript()).append("</script>");
        s.append("</body></html>");
        return s.toString();
    }

    // ── Sections ─────────────────────────────────────────────────────────────

    private static void header(StringBuilder s, SessionData d) {
        s.append("<table><tr><th>Start (time signature)</th><td>").append(esc(d.startUtc))
                .append(" <span class=\"sub\">(epoch ").append(d.startEpochMs).append(")</span></td></tr>");
        s.append("<tr><th>End (time signature)</th><td>").append(esc(d.endUtc))
                .append(" <span class=\"sub\">(epoch ").append(d.endEpochMs).append(")</span></td></tr>");
        long durS = Math.max(0, (d.endEpochMs - d.startEpochMs) / 1000);
        s.append("<tr><th>Duration</th><td>").append(durS / 60).append("m ").append(durS % 60).append("s</td></tr>");
        s.append("<tr><th>Player UUID</th><td>").append(esc(d.playerUuid)).append("</td></tr>");
        if (!d.opponents.isEmpty()) {
            s.append("<tr><th>Opponents</th><td>").append(esc(String.join(", ", d.opponents))).append("</td></tr>");
        }
        s.append("</table>");
    }

    private static void jumpSection(StringBuilder s, SessionData d) {
        s.append("<h2>Jump resets</h2><div class=\"cards\">");
        card(s, Integer.toString(d.jumpAttempts), "attempts");
        card(s, Integer.toString(d.jumpHits), "hits");
        card(s, Integer.toString(d.jumpMisses), "misses");
        card(s, fmt(d.jumpAvgMs) + " ms", "avg delta");
        card(s, fmt(d.jumpSdMs) + " ms", "std dev");
        s.append("</div>");
        s.append(timeChart("Jump-reset delta over time (ms)", d.jumpEvents, d.startEpochMs, d.endEpochMs));
    }

    private static void comboSection(StringBuilder s, SessionData d) {
        s.append("<h2>Combo timing</h2><div class=\"cards\">");
        card(s, Integer.toString(d.combos), "combos");
        card(s, Integer.toString(d.comboIntervals), "intervals");
        card(s, fmt(d.comboAvgMs) + " ms", "avg interval");
        card(s, fmt(d.comboJitterMs) + " ms", "jitter (SD)");
        s.append("</div>");
        s.append("<div class=\"sub\">Low jitter relative to the average suggests automated (triggerbot) timing; "
                + "a human combo shows wider spread.</div>");
        s.append(comboChart(d));
    }

    private static void reachSection(StringBuilder s, SessionData d) {
        s.append("<h2>Reach</h2><div class=\"cards\">");
        card(s, Integer.toString(d.swings), "swings");
        card(s, Integer.toString(d.swingHits), "landed");
        card(s, Integer.toString(d.swingMisses), "whiffed");
        card(s, fmt(d.reachAvgBlocks) + " b", "avg reach");
        card(s, fmt(d.reachMaxBlocks) + " b", "max reach");
        card(s, fmt(d.reachSdBlocks) + " b", "std dev");
        s.append("</div>");
        s.append("<div class=\"sub\">Distance from your eyes to the target's hitbox on every swing. Green landed, "
                + "red whiffed. The dashed line is vanilla melee range (3.0 blocks) &mdash; consistently landing "
                + "hits well beyond it is what a reach cheat looks like.</div>");
        s.append(reachChart(d));
    }

    private static void aimSection(StringBuilder s, SessionData d) {
        s.append("<h2>Aim placement</h2><div class=\"cards\">");
        card(s, fmt(d.aimAvgDeg) + "&deg;", "avg off-centre");
        card(s, fmt(d.aimSdDeg) + "&deg;", "std dev");
        s.append("</div>");
        s.append("<div class=\"sub\">Where your crosshair sat relative to the middle of the target's hitbox, drawn "
                + "to scale (0.6 &times; 1.8 blocks). Human aim scatters across the box; a tight cluster on dead "
                + "centre is what an aim assist looks like. <b>Spread here is the point</b> &mdash; it is evidence "
                + "for you, not against you.</div>");
        s.append(aimScatter(d));
    }

    private static void integritySection(StringBuilder s, String sha, String sig, String canonical) {
        s.append("<h2>Integrity</h2><div class=\"intg\">");
        s.append("Algorithm: SHA-256 + HMAC-SHA256<br>SHA-256: ").append(esc(sha))
                .append("<br>Signature: ").append(esc(sig));
        s.append("<br><span class=\"warn\">Note:</span> the signing key ships inside the open-source mod, so this "
                + "detects casual edits but is <b>not</b> unforgeable. Verify by recomputing SHA-256 over the exact "
                + "canonicalData string below (UTF-8).");
        s.append("<br><br><span class=\"warn\">On reach and aim:</span> these are measured on <b>your</b> client. "
                + "Other players' positions are interpolated locally, and the server saw them somewhere slightly "
                + "different depending on latency, so these figures will not match a server-side anti-cheat's "
                + "exactly. Read them as evidence of how you play, not as the server's own record.</div>");
        s.append("<details><summary>Canonical data (hashed bytes)</summary><pre>")
                .append(esc(canonical)).append("</pre></details>");
    }

    // ── Charts ───────────────────────────────────────────────────────────────

    private static final int W = 720;
    private static final int H = 260;
    private static final int ML = 48;
    private static final int MR = 16;
    private static final int MT = 28;
    private static final int MB = 30;

    private static String timeChart(String title, List<SessionData.JEvent> pts, long startMs, long endMs) {
        StringBuilder s = svgOpen(W, H);
        title(s, title);
        if (pts.isEmpty()) {
            return noData(s);
        }
        double yMin = 0, yMax = 1;
        for (SessionData.JEvent p : pts) {
            yMax = Math.max(yMax, p.deltaMs);
            yMin = Math.min(yMin, p.deltaMs);
        }
        yMax = yMax * 1.1 + 1;
        long span = Math.max(1, endMs - startMs);
        axes(s, yMin, yMax);

        int pw = W - ML - MR, ph = H - MT - MB;
        StringBuilder poly = new StringBuilder();
        StringBuilder dots = new StringBuilder();
        for (SessionData.JEvent p : pts) {
            int x = (int) (ML + (double) (p.t - startMs) / span * pw);
            int y = (int) (MT + ph - (p.deltaMs - yMin) / (yMax - yMin) * ph);
            poly.append(x).append(",").append(y).append(" ");
            boolean ok = "SUCCESS".equals(p.result);
            String tip = offset(p.t - startMs) + " : " + p.deltaMs + " ms"
                    + (p.result != null ? " (" + p.result + ")" : "");
            dot(dots, x, y, ok ? HIT_COLOR : MISS_COLOR, tip);
        }
        s.append("<polyline points=\"").append(poly.toString().trim())
                .append("\" fill=\"none\" stroke=\"#4caf50\" stroke-opacity=\"0.35\" stroke-width=\"1\"/>");
        s.append(dots).append("</svg>");
        return s.toString();
    }

    private static String comboChart(SessionData d) {
        StringBuilder s = svgOpen(W, H);
        title(s, "Combo inter-hit interval over time (ms)");
        if (d.comboEvents.isEmpty()) {
            return noData(s);
        }
        double yMin = 0, yMax = 1;
        for (SessionData.CEvent c : d.comboEvents) {
            yMax = Math.max(yMax, c.intervalMs);
        }
        yMax = yMax * 1.1 + 1;
        long span = Math.max(1, d.endEpochMs - d.startEpochMs);
        axes(s, yMin, yMax);

        int pw = W - ML - MR, ph = H - MT - MB;
        StringBuilder poly = new StringBuilder();
        StringBuilder dots = new StringBuilder();
        for (SessionData.CEvent c : d.comboEvents) {
            int x = (int) (ML + (double) (c.t - d.startEpochMs) / span * pw);
            int y = (int) (MT + ph - (c.intervalMs - yMin) / (yMax - yMin) * ph);
            poly.append(x).append(",").append(y).append(" ");
            dot(dots, x, y, COMBO_COLOR, offset(c.t - d.startEpochMs) + " : " + c.intervalMs + " ms");
        }
        s.append("<polyline points=\"").append(poly.toString().trim())
                .append("\" fill=\"none\" stroke=\"#29b6f6\" stroke-opacity=\"0.5\" stroke-width=\"1\"/>");
        s.append(dots).append("</svg>");
        return s.toString();
    }

    private static String reachChart(SessionData d) {
        StringBuilder s = svgOpen(W, H);
        title(s, "Reach per swing (blocks)");
        if (d.swingEvents.isEmpty()) {
            return noData(s);
        }
        double yMax = VANILLA_REACH;
        for (SessionData.SEvent e : d.swingEvents) {
            yMax = Math.max(yMax, e.reach);
        }
        yMax = yMax * 1.15;
        long span = Math.max(1, d.endEpochMs - d.startEpochMs);
        axes(s, 0, yMax);

        int pw = W - ML - MR, ph = H - MT - MB;

        // Vanilla-range reference line.
        int refY = (int) (MT + ph - VANILLA_REACH / yMax * ph);
        s.append("<line x1=\"").append(ML).append("\" y1=\"").append(refY).append("\" x2=\"").append(ML + pw)
                .append("\" y2=\"").append(refY)
                .append("\" stroke=\"#ffb454\" stroke-width=\"1\" stroke-dasharray=\"4 4\"/>");
        s.append("<text x=\"").append(ML + pw).append("\" y=\"").append(refY - 4)
                .append("\" fill=\"#ffb454\" font-size=\"10\" text-anchor=\"end\" font-family=\"sans-serif\">")
                .append("vanilla 3.0</text>");

        StringBuilder dots = new StringBuilder();
        for (SessionData.SEvent e : d.swingEvents) {
            int x = (int) (ML + (double) (e.t - d.startEpochMs) / span * pw);
            int y = (int) (MT + ph - e.reach / yMax * ph);
            String who = e.target >= 0 && e.target < d.opponents.size() ? " vs " + d.opponents.get(e.target) : "";
            dot(dots, x, y, e.hit ? HIT_COLOR : MISS_COLOR,
                    offset(e.t - d.startEpochMs) + " : " + fmt(e.reach) + " blocks "
                            + (e.hit ? "(landed)" : "(whiffed)") + who);
        }
        s.append(dots).append("</svg>");
        return s.toString();
    }

    /**
     * Scatter of aim offsets with the hitbox drawn to scale. Both axes share one
     * scale so the box keeps its real 0.6 x 1.8 proportions — squashing it to fill
     * the frame would make centred aim look more spread out than it is.
     */
    private static String aimScatter(SessionData d) {
        int w = 420, h = 460, ml = 44, mr = 16, mt = 28, mb = 34;
        int pw = w - ml - mr, ph = h - mt - mb;
        StringBuilder s = svgOpen(w, h);
        title(s, "Aim offset from hitbox centre (blocks)");
        if (d.swingEvents.isEmpty()) {
            return noData(s, w, h);
        }

        double halfW = HITBOX_HALF_W * 1.6;
        double halfH = HITBOX_HALF_H * 1.25;
        for (SessionData.SEvent e : d.swingEvents) {
            halfW = Math.max(halfW, Math.abs(e.offX) * 1.1);
            halfH = Math.max(halfH, Math.abs(e.offY) * 1.1);
        }
        // One scale for both axes keeps the hitbox honest.
        double scale = Math.min(pw / (2 * halfW), ph / (2 * halfH));
        double cx = ml + pw / 2.0;
        double cy = mt + ph / 2.0;

        // Hitbox outline.
        double bw = HITBOX_HALF_W * scale, bh = HITBOX_HALF_H * scale;
        s.append("<rect x=\"").append(r(cx - bw)).append("\" y=\"").append(r(cy - bh))
                .append("\" width=\"").append(r(bw * 2)).append("\" height=\"").append(r(bh * 2))
                .append("\" fill=\"#4caf50\" fill-opacity=\"0.06\" stroke=\"#4a5561\" stroke-width=\"1\"/>");
        // Centre crosshair.
        s.append("<line x1=\"").append(r(cx)).append("\" y1=\"").append(mt).append("\" x2=\"").append(r(cx))
                .append("\" y2=\"").append(mt + ph).append("\" stroke=\"#2a2f37\"/>");
        s.append("<line x1=\"").append(ml).append("\" y1=\"").append(r(cy)).append("\" x2=\"").append(ml + pw)
                .append("\" y2=\"").append(r(cy)).append("\" stroke=\"#2a2f37\"/>");

        StringBuilder dots = new StringBuilder();
        for (SessionData.SEvent e : d.swingEvents) {
            double x = cx + e.offX * scale;
            double y = cy - e.offY * scale;
            String who = e.target >= 0 && e.target < d.opponents.size() ? " vs " + d.opponents.get(e.target) : "";
            dots.append("<circle cx=\"").append(r(x)).append("\" cy=\"").append(r(y))
                    .append("\" r=\"3\" fill=\"").append(hex(e.hit ? HIT_COLOR : MISS_COLOR))
                    .append("\" fill-opacity=\"0.75\"><title>")
                    .append(esc(fmt(e.offX) + ", " + fmt(e.offY) + " blocks / " + fmt(e.aimDeg) + " deg" + who))
                    .append("</title></circle>");
        }
        s.append(dots);
        s.append("<text x=\"").append(ml).append("\" y=\"").append(h - 10)
                .append("\" fill=\"#6b7480\" font-size=\"10\" font-family=\"sans-serif\">")
                .append("box = player hitbox to scale &middot; green landed, red whiffed</text>");
        s.append("</svg>");
        return s.toString();
    }

    // ── SVG helpers ──────────────────────────────────────────────────────────

    private static StringBuilder svgOpen(int w, int h) {
        StringBuilder s = new StringBuilder(2048);
        s.append("<svg class=\"chart\" viewBox=\"0 0 ").append(w).append(" ").append(h)
                .append("\" width=\"100%\" style=\"max-width:").append(w + 40)
                .append("px;background:#161a20;border:1px solid #2a2f37;border-radius:8px;cursor:grab;")
                .append("touch-action:none;\">");
        return s;
    }

    private static void title(StringBuilder s, String text) {
        s.append("<text x=\"").append(ML).append("\" y=\"18\" fill=\"#9fb3c8\" font-size=\"13\" ")
                .append("font-family=\"sans-serif\">").append(esc(text)).append("</text>");
    }

    private static String noData(StringBuilder s) {
        return noData(s, W, H);
    }

    private static String noData(StringBuilder s, int w, int h) {
        s.append("<text x=\"").append(w / 2).append("\" y=\"").append(h / 2)
                .append("\" fill=\"#5f6772\" font-size=\"13\" text-anchor=\"middle\" ")
                .append("font-family=\"sans-serif\">no data recorded</text></svg>");
        return s.toString();
    }

    private static void axes(StringBuilder s, double yMin, double yMax) {
        int pw = W - ML - MR, ph = H - MT - MB;
        s.append("<line x1=\"").append(ML).append("\" y1=\"").append(MT).append("\" x2=\"").append(ML)
                .append("\" y2=\"").append(MT + ph).append("\" stroke=\"#2a2f37\"/>");
        s.append("<line x1=\"").append(ML).append("\" y1=\"").append(MT + ph).append("\" x2=\"").append(ML + pw)
                .append("\" y2=\"").append(MT + ph).append("\" stroke=\"#2a2f37\"/>");
        for (int i = 0; i <= 2; i++) {
            double val = yMin + (yMax - yMin) * i / 2.0;
            int yy = (int) (MT + ph - (val - yMin) / (yMax - yMin) * ph);
            s.append("<line x1=\"").append(ML - 3).append("\" y1=\"").append(yy).append("\" x2=\"").append(ML + pw)
                    .append("\" y2=\"").append(yy).append("\" stroke=\"#21262e\"/>");
            s.append("<text x=\"").append(ML - 6).append("\" y=\"").append(yy + 3)
                    .append("\" fill=\"#6b7480\" font-size=\"10\" text-anchor=\"end\" font-family=\"sans-serif\">")
                    .append(tick(val)).append("</text>");
        }
    }

    private static void dot(StringBuilder s, int x, int y, int color, String tip) {
        s.append("<circle cx=\"").append(x).append("\" cy=\"").append(y).append("\" r=\"3\" fill=\"")
                .append(hex(color)).append("\"><title>").append(esc(tip)).append("</title></circle>");
    }

    private static String panZoomScript() {
        return "document.querySelectorAll('svg.chart').forEach(function(svg){"
                + "var vb=svg.getAttribute('viewBox').split(' ').map(Number);var init=vb.slice();"
                + "var v={x:vb[0],y:vb[1],w:vb[2],h:vb[3]};"
                + "function ap(){svg.setAttribute('viewBox',v.x+' '+v.y+' '+v.w+' '+v.h);}"
                + "svg.addEventListener('wheel',function(e){e.preventDefault();var r=svg.getBoundingClientRect();"
                + "var mx=v.x+(e.clientX-r.left)/r.width*v.w;var my=v.y+(e.clientY-r.top)/r.height*v.h;"
                + "var f=e.deltaY<0?0.85:1/0.85;v.w*=f;v.h*=f;"
                + "v.x=mx-(e.clientX-r.left)/r.width*v.w;v.y=my-(e.clientY-r.top)/r.height*v.h;ap();},{passive:false});"
                + "var d=false,lx=0,ly=0;"
                + "svg.addEventListener('mousedown',function(e){d=true;lx=e.clientX;ly=e.clientY;svg.style.cursor='grabbing';});"
                + "window.addEventListener('mousemove',function(e){if(!d)return;var r=svg.getBoundingClientRect();"
                + "v.x-=(e.clientX-lx)/r.width*v.w;v.y-=(e.clientY-ly)/r.height*v.h;lx=e.clientX;ly=e.clientY;ap();});"
                + "window.addEventListener('mouseup',function(){d=false;svg.style.cursor='grab';});"
                + "svg.addEventListener('dblclick',function(){v={x:init[0],y:init[1],w:init[2],h:init[3]};ap();});"
                + "});";
    }

    private static String css() {
        return "body{font-family:system-ui,Segoe UI,Arial,sans-serif;background:#14161a;color:#e8eaed;margin:0;padding:24px;}"
                + "h1{font-size:20px;margin:0 0 4px;}h2{font-size:15px;margin:24px 0 8px;color:#9fb3c8;}"
                + ".sub{color:#8a93a0;font-size:13px;margin-bottom:16px;max-width:760px;line-height:1.5;}"
                + "table{border-collapse:collapse;font-size:13px;margin:4px 0;}"
                + "td,th{border:1px solid #2a2f37;padding:4px 10px;text-align:left;}"
                + "th{background:#1c2026;color:#9fb3c8;}"
                + ".cards{display:flex;flex-wrap:wrap;gap:12px;margin:8px 0;}"
                + ".card{background:#1c2026;border:1px solid #2a2f37;border-radius:8px;padding:10px 16px;min-width:110px;}"
                + ".card .v{font-size:22px;font-weight:600;}.card .k{font-size:12px;color:#8a93a0;}"
                + ".intg{background:#161a20;border:1px solid #2a2f37;border-radius:8px;padding:12px;"
                + "font-family:ui-monospace,Consolas,monospace;font-size:12px;word-break:break-all;max-width:760px;line-height:1.6;}"
                + ".warn{color:#ffb454;}circle:hover{stroke:#fff;stroke-width:1.5;}"
                + "details{margin-top:8px;}pre{white-space:pre-wrap;word-break:break-all;background:#0f1114;"
                + "padding:10px;border-radius:6px;font-size:11px;max-width:760px;}";
    }

    // ── Formatting ───────────────────────────────────────────────────────────

    private static void card(StringBuilder s, String value, String key) {
        s.append("<div class=\"card\"><div class=\"v\">").append(value).append("</div><div class=\"k\">")
                .append(key).append("</div></div>");
    }

    private static String offset(long ms) {
        return "+" + (ms / 1000) + "." + String.format("%03d", Math.abs(ms % 1000)) + "s";
    }

    private static String tick(double v) {
        return Math.abs(v) >= 10 ? Long.toString(Math.round(v)) : fmt(v);
    }

    private static String hex(int rgb) {
        return String.format("#%06x", rgb & 0xFFFFFF);
    }

    private static String r(double v) {
        return String.format("%.1f", v);
    }

    static String fmt(double v) {
        return String.format("%.2f", v);
    }

    static String esc(String in) {
        if (in == null) {
            return "";
        }
        return in.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;");
    }
}
